version: '3.7'
x-app: &app
  build:
    context: .
    dockerfile: Dockerfile
  image: django-tutorial:1.0.0

x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true
  environment:
    DB_ENGINE: django.db.backends.postgresql
    DB_NAME: example_db
    DB_USER: postgres
    DB_PASSWORD: postgres
    DB_HOST: postgres
    DB_PORT: 5432
  volumes:
    - .:/code:cached
    - pip:/usr/local/lib/python2.7/site-packages
  depends_on:
    - postgres

services:
  runner:
    <<: *backend
    command: /bin/bash
  django:
    <<: *backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"


  postgres:
    image: postgres:13
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: example_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s
volumes:
  postgres:
  pip:
